-- MySQL Script generated by MySQL Workbench
-- 09/21/15 16:14:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lsed_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lsed_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lsed_db` DEFAULT CHARACTER SET utf8 ;
USE `lsed_db` ;

-- -----------------------------------------------------
-- Table `lsed_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`user` (
  `UserId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Username` VARCHAR(32) NOT NULL COMMENT '',
  `Email` VARCHAR(64) NOT NULL COMMENT '',
  `Password` VARCHAR(128) NOT NULL COMMENT '',
  `FullName` VARCHAR(48) NOT NULL COMMENT '',
  `FavoriteColor` VARCHAR(8) NOT NULL COMMENT '',
  `FavoriteActivity` VARCHAR(16) NOT NULL COMMENT '',
  PRIMARY KEY (`UserId`)  COMMENT '',
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lsed_db`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`card` (
  `CardId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `USER_UserId` INT(11) NOT NULL COMMENT '',
  `Title` VARCHAR(64) NOT NULL COMMENT '',
  `DateCreated` DATE NOT NULL COMMENT '',
  `DateModified` DATE NOT NULL COMMENT '',
  `Description` VARCHAR(320) NULL DEFAULT NULL COMMENT '',
  `ImageLink` VARCHAR(256) NOT NULL COMMENT '',
  `EmbedLink` VARCHAR(256) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`CardId`, `USER_UserId`)  COMMENT '',
  INDEX `fk_CARD_USER1_idx` (`USER_UserId` ASC)  COMMENT '',
  CONSTRAINT `fk_CARD_USER1`
    FOREIGN KEY (`USER_UserId`)
    REFERENCES `lsed_db`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lsed_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`category` (
  `CategoryId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Category` VARCHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`CategoryId`)  COMMENT '',
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lsed_db`.`card_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`card_category` (
  `CardCategoryId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `CATEGORY_CategoryId` INT(11) NOT NULL COMMENT '',
  `CARD_CardId` INT(11) NOT NULL COMMENT '',
  `CARD_USER_UserId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`CardCategoryId`, `CATEGORY_CategoryId`, `CARD_CardId`, `CARD_USER_UserId`)  COMMENT '',
  INDEX `fk_CARD_CATEGORY_CATEGORY1_idx` (`CATEGORY_CategoryId` ASC)  COMMENT '',
  INDEX `fk_CARD_CATEGORY_CARD1_idx` (`CARD_CardId` ASC, `CARD_USER_UserId` ASC)  COMMENT '',
  CONSTRAINT `fk_CARD_CATEGORY_CARD1`
    FOREIGN KEY (`CARD_CardId` , `CARD_USER_UserId`)
    REFERENCES `lsed_db`.`card` (`CardId` , `USER_UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARD_CATEGORY_CATEGORY1`
    FOREIGN KEY (`CATEGORY_CategoryId`)
    REFERENCES `lsed_db`.`category` (`CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lsed_db`.`prerequisite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`prerequisite` (
  `PrerequisiteId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Prerequisite` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`PrerequisiteId`)  COMMENT '',
  UNIQUE INDEX `Prerequisite_UNIQUE` (`Prerequisite` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lsed_db`.`card_prerequisite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`card_prerequisite` (
  `CardPrerequisiteId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `CARD_CardId` INT(11) NOT NULL COMMENT '',
  `CARD_USER_UserId` INT(11) NOT NULL COMMENT '',
  `PREREQUISITE_PrerequisiteId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`CardPrerequisiteId`, `CARD_CardId`, `CARD_USER_UserId`, `PREREQUISITE_PrerequisiteId`)  COMMENT '',
  INDEX `fk_CARD_PREREQUISITE_CARD1_idx` (`CARD_CardId` ASC, `CARD_USER_UserId` ASC)  COMMENT '',
  INDEX `fk_CARD_PREREQUISITE_PREREQUISITE1_idx` (`PREREQUISITE_PrerequisiteId` ASC)  COMMENT '',
  CONSTRAINT `fk_CARD_PREREQUISITE_CARD1`
    FOREIGN KEY (`CARD_CardId` , `CARD_USER_UserId`)
    REFERENCES `lsed_db`.`card` (`CardId` , `USER_UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARD_PREREQUISITE_PREREQUISITE1`
    FOREIGN KEY (`PREREQUISITE_PrerequisiteId`)
    REFERENCES `lsed_db`.`prerequisite` (`PrerequisiteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

USE `lsed_db` ;

-- -----------------------------------------------------
-- procedure queryCardInfo_SortBy
-- -----------------------------------------------------

DELIMITER $$
USE `lsed_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `queryCardInfo_SortBy`(IN sortparam VARCHAR(50))
BEGIN
	SELECT CARD.Title, 
           CARD.Description, 
		   CARD.DateCreated, 
           CARD.DateModified, 
           CARD.ImageLink, 
           CARD.EmbedLink
    FROM CARD
    ORDER BY CASE WHEN sortparam = 'Title' THEN Title
                  WHEN sortparam = 'Description' THEN Description
	              WHEN sortparam = 'DateCreated' THEN DateCreated
	              WHEN sortparam = 'DateModified' THEN DateModified
	              WHEN sortparam = 'ImageLink' THEN ImageLink
	              WHEN sortparam = 'EmbedLink' THEN EmbedLink
                  ELSE Title
			 END ASC;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
