-- MySQL Script generated by MySQL Workbench
-- 07/13/15 12:22:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lsed_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lsed_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lsed_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lsed_db` ;

-- -----------------------------------------------------
-- Table `lsed_db`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`USER` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(32) NOT NULL,
  `Email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsed_db`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`CATEGORY` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`CategoryId`),
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsed_db`.`CARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`CARD` (
  `CardId` INT NOT NULL AUTO_INCREMENT,
  `USER_UserId` INT NOT NULL,
  `Title` VARCHAR(64) NOT NULL,
  `DateCreated` DATE NOT NULL,
  `DateModified` DATE NOT NULL,
  `Description` VARCHAR(320) NULL,
  `ImageLink` VARCHAR(256) NOT NULL,
  `EmbedLink` VARCHAR(256) NULL,
  PRIMARY KEY (`CardId`, `USER_UserId`),
  INDEX `fk_CARD_USER1_idx` (`USER_UserId` ASC),
  CONSTRAINT `fk_CARD_USER1`
    FOREIGN KEY (`USER_UserId`)
    REFERENCES `lsed_db`.`USER` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsed_db`.`CARD_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`CARD_CATEGORY` (
  `CardCategoryId` INT NOT NULL AUTO_INCREMENT,
  `CATEGORY_CategoryId` INT NOT NULL,
  `CARD_CardId` INT NOT NULL,
  `CARD_USER_UserId` INT NOT NULL,
  PRIMARY KEY (`CardCategoryId`, `CATEGORY_CategoryId`, `CARD_CardId`, `CARD_USER_UserId`),
  INDEX `fk_CARD_CATEGORY_CATEGORY1_idx` (`CATEGORY_CategoryId` ASC),
  INDEX `fk_CARD_CATEGORY_CARD1_idx` (`CARD_CardId` ASC, `CARD_USER_UserId` ASC),
  CONSTRAINT `fk_CARD_CATEGORY_CATEGORY1`
    FOREIGN KEY (`CATEGORY_CategoryId`)
    REFERENCES `lsed_db`.`CATEGORY` (`CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARD_CATEGORY_CARD1`
    FOREIGN KEY (`CARD_CardId` , `CARD_USER_UserId`)
    REFERENCES `lsed_db`.`CARD` (`CardId` , `USER_UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsed_db`.`PREREQUISITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`PREREQUISITE` (
  `PrerequisiteId` INT NOT NULL AUTO_INCREMENT,
  `Prerequisite` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`PrerequisiteId`),
  UNIQUE INDEX `Prerequisite_UNIQUE` (`Prerequisite` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsed_db`.`CARD_PREREQUISITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsed_db`.`CARD_PREREQUISITE` (
  `CardPrerequisiteId` INT NOT NULL AUTO_INCREMENT,
  `CARD_CardId` INT NOT NULL,
  `CARD_USER_UserId` INT NOT NULL,
  `PREREQUISITE_PrerequisiteId` INT NOT NULL,
  PRIMARY KEY (`CardPrerequisiteId`, `CARD_CardId`, `CARD_USER_UserId`, `PREREQUISITE_PrerequisiteId`),
  INDEX `fk_CARD_PREREQUISITE_CARD1_idx` (`CARD_CardId` ASC, `CARD_USER_UserId` ASC),
  INDEX `fk_CARD_PREREQUISITE_PREREQUISITE1_idx` (`PREREQUISITE_PrerequisiteId` ASC),
  CONSTRAINT `fk_CARD_PREREQUISITE_CARD1`
    FOREIGN KEY (`CARD_CardId` , `CARD_USER_UserId`)
    REFERENCES `lsed_db`.`CARD` (`CardId` , `USER_UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARD_PREREQUISITE_PREREQUISITE1`
    FOREIGN KEY (`PREREQUISITE_PrerequisiteId`)
    REFERENCES `lsed_db`.`PREREQUISITE` (`PrerequisiteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
